/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutLeftDetailImport } from './routes/_layout/_left-detail'
import { Route as LayoutNearbyAmenitySplatImport } from './routes/_layout/nearby.$amenity.$'
import { Route as LayoutLeftDetailPlaceOsmIdSplatImport } from './routes/_layout/_left-detail.place.$osmId.$'
import { Route as LayoutLeftDetailEventsMadhyapurFestivalSplatImport } from './routes/_layout/_left-detail.events.madhyapur-festival.$'

// Create Virtual Routes

const LayoutContributionsLazyImport = createFileRoute(
  '/_layout/contributions',
)()
const LayoutSplatLazyImport = createFileRoute('/_layout/$')()
const LayoutReportIncidentSplatLazyImport = createFileRoute(
  '/_layout/report-incident/$',
)()
const LayoutAddPlaceSplatLazyImport = createFileRoute('/_layout/add-place/$')()
const LayoutLeftDetailPlacesPlaceIdLazyImport = createFileRoute(
  '/_layout/_left-detail/places/$placeId',
)()
const LayoutDirectionsLocationsModeSplatLazyImport = createFileRoute(
  '/_layout/directions/$locations/$mode/$',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutContributionsLazyRoute = LayoutContributionsLazyImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/contributions.lazy').then((d) => d.Route),
)

const LayoutSplatLazyRoute = LayoutSplatLazyImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/$.lazy').then((d) => d.Route))

const LayoutLeftDetailRoute = LayoutLeftDetailImport.update({
  id: '/_left-detail',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportIncidentSplatLazyRoute =
  LayoutReportIncidentSplatLazyImport.update({
    id: '/report-incident/$',
    path: '/report-incident/$',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/report-incident/$.lazy').then((d) => d.Route),
  )

const LayoutAddPlaceSplatLazyRoute = LayoutAddPlaceSplatLazyImport.update({
  id: '/add-place/$',
  path: '/add-place/$',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/add-place/$.lazy').then((d) => d.Route),
)

const LayoutLeftDetailPlacesPlaceIdLazyRoute =
  LayoutLeftDetailPlacesPlaceIdLazyImport.update({
    id: '/places/$placeId',
    path: '/places/$placeId',
    getParentRoute: () => LayoutLeftDetailRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_left-detail.places.$placeId.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutNearbyAmenitySplatRoute = LayoutNearbyAmenitySplatImport.update({
  id: '/nearby/$amenity/$',
  path: '/nearby/$amenity/$',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDirectionsLocationsModeSplatLazyRoute =
  LayoutDirectionsLocationsModeSplatLazyImport.update({
    id: '/directions/$locations/$mode/$',
    path: '/directions/$locations/$mode/$',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/directions.$locations.$mode.$.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutLeftDetailPlaceOsmIdSplatRoute =
  LayoutLeftDetailPlaceOsmIdSplatImport.update({
    id: '/place/$osmId/$',
    path: '/place/$osmId/$',
    getParentRoute: () => LayoutLeftDetailRoute,
  } as any)

const LayoutLeftDetailEventsMadhyapurFestivalSplatRoute =
  LayoutLeftDetailEventsMadhyapurFestivalSplatImport.update({
    id: '/events/madhyapur-festival/$',
    path: '/events/madhyapur-festival/$',
    getParentRoute: () => LayoutLeftDetailRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_left-detail': {
      id: '/_layout/_left-detail'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutLeftDetailImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$': {
      id: '/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof LayoutSplatLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contributions': {
      id: '/_layout/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof LayoutContributionsLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/add-place/$': {
      id: '/_layout/add-place/$'
      path: '/add-place/$'
      fullPath: '/add-place/$'
      preLoaderRoute: typeof LayoutAddPlaceSplatLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/report-incident/$': {
      id: '/_layout/report-incident/$'
      path: '/report-incident/$'
      fullPath: '/report-incident/$'
      preLoaderRoute: typeof LayoutReportIncidentSplatLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/nearby/$amenity/$': {
      id: '/_layout/nearby/$amenity/$'
      path: '/nearby/$amenity/$'
      fullPath: '/nearby/$amenity/$'
      preLoaderRoute: typeof LayoutNearbyAmenitySplatImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_left-detail/places/$placeId': {
      id: '/_layout/_left-detail/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof LayoutLeftDetailPlacesPlaceIdLazyImport
      parentRoute: typeof LayoutLeftDetailImport
    }
    '/_layout/_left-detail/events/madhyapur-festival/$': {
      id: '/_layout/_left-detail/events/madhyapur-festival/$'
      path: '/events/madhyapur-festival/$'
      fullPath: '/events/madhyapur-festival/$'
      preLoaderRoute: typeof LayoutLeftDetailEventsMadhyapurFestivalSplatImport
      parentRoute: typeof LayoutLeftDetailImport
    }
    '/_layout/_left-detail/place/$osmId/$': {
      id: '/_layout/_left-detail/place/$osmId/$'
      path: '/place/$osmId/$'
      fullPath: '/place/$osmId/$'
      preLoaderRoute: typeof LayoutLeftDetailPlaceOsmIdSplatImport
      parentRoute: typeof LayoutLeftDetailImport
    }
    '/_layout/directions/$locations/$mode/$': {
      id: '/_layout/directions/$locations/$mode/$'
      path: '/directions/$locations/$mode/$'
      fullPath: '/directions/$locations/$mode/$'
      preLoaderRoute: typeof LayoutDirectionsLocationsModeSplatLazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutLeftDetailRouteChildren {
  LayoutLeftDetailPlacesPlaceIdLazyRoute: typeof LayoutLeftDetailPlacesPlaceIdLazyRoute
  LayoutLeftDetailEventsMadhyapurFestivalSplatRoute: typeof LayoutLeftDetailEventsMadhyapurFestivalSplatRoute
  LayoutLeftDetailPlaceOsmIdSplatRoute: typeof LayoutLeftDetailPlaceOsmIdSplatRoute
}

const LayoutLeftDetailRouteChildren: LayoutLeftDetailRouteChildren = {
  LayoutLeftDetailPlacesPlaceIdLazyRoute:
    LayoutLeftDetailPlacesPlaceIdLazyRoute,
  LayoutLeftDetailEventsMadhyapurFestivalSplatRoute:
    LayoutLeftDetailEventsMadhyapurFestivalSplatRoute,
  LayoutLeftDetailPlaceOsmIdSplatRoute: LayoutLeftDetailPlaceOsmIdSplatRoute,
}

const LayoutLeftDetailRouteWithChildren =
  LayoutLeftDetailRoute._addFileChildren(LayoutLeftDetailRouteChildren)

interface LayoutRouteChildren {
  LayoutLeftDetailRoute: typeof LayoutLeftDetailRouteWithChildren
  LayoutSplatLazyRoute: typeof LayoutSplatLazyRoute
  LayoutContributionsLazyRoute: typeof LayoutContributionsLazyRoute
  LayoutAddPlaceSplatLazyRoute: typeof LayoutAddPlaceSplatLazyRoute
  LayoutReportIncidentSplatLazyRoute: typeof LayoutReportIncidentSplatLazyRoute
  LayoutNearbyAmenitySplatRoute: typeof LayoutNearbyAmenitySplatRoute
  LayoutDirectionsLocationsModeSplatLazyRoute: typeof LayoutDirectionsLocationsModeSplatLazyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLeftDetailRoute: LayoutLeftDetailRouteWithChildren,
  LayoutSplatLazyRoute: LayoutSplatLazyRoute,
  LayoutContributionsLazyRoute: LayoutContributionsLazyRoute,
  LayoutAddPlaceSplatLazyRoute: LayoutAddPlaceSplatLazyRoute,
  LayoutReportIncidentSplatLazyRoute: LayoutReportIncidentSplatLazyRoute,
  LayoutNearbyAmenitySplatRoute: LayoutNearbyAmenitySplatRoute,
  LayoutDirectionsLocationsModeSplatLazyRoute:
    LayoutDirectionsLocationsModeSplatLazyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutLeftDetailRouteWithChildren
  '/$': typeof LayoutSplatLazyRoute
  '/contributions': typeof LayoutContributionsLazyRoute
  '/add-place/$': typeof LayoutAddPlaceSplatLazyRoute
  '/report-incident/$': typeof LayoutReportIncidentSplatLazyRoute
  '/nearby/$amenity/$': typeof LayoutNearbyAmenitySplatRoute
  '/places/$placeId': typeof LayoutLeftDetailPlacesPlaceIdLazyRoute
  '/events/madhyapur-festival/$': typeof LayoutLeftDetailEventsMadhyapurFestivalSplatRoute
  '/place/$osmId/$': typeof LayoutLeftDetailPlaceOsmIdSplatRoute
  '/directions/$locations/$mode/$': typeof LayoutDirectionsLocationsModeSplatLazyRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutLeftDetailRouteWithChildren
  '/$': typeof LayoutSplatLazyRoute
  '/contributions': typeof LayoutContributionsLazyRoute
  '/add-place/$': typeof LayoutAddPlaceSplatLazyRoute
  '/report-incident/$': typeof LayoutReportIncidentSplatLazyRoute
  '/nearby/$amenity/$': typeof LayoutNearbyAmenitySplatRoute
  '/places/$placeId': typeof LayoutLeftDetailPlacesPlaceIdLazyRoute
  '/events/madhyapur-festival/$': typeof LayoutLeftDetailEventsMadhyapurFestivalSplatRoute
  '/place/$osmId/$': typeof LayoutLeftDetailPlaceOsmIdSplatRoute
  '/directions/$locations/$mode/$': typeof LayoutDirectionsLocationsModeSplatLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_left-detail': typeof LayoutLeftDetailRouteWithChildren
  '/_layout/$': typeof LayoutSplatLazyRoute
  '/_layout/contributions': typeof LayoutContributionsLazyRoute
  '/_layout/add-place/$': typeof LayoutAddPlaceSplatLazyRoute
  '/_layout/report-incident/$': typeof LayoutReportIncidentSplatLazyRoute
  '/_layout/nearby/$amenity/$': typeof LayoutNearbyAmenitySplatRoute
  '/_layout/_left-detail/places/$placeId': typeof LayoutLeftDetailPlacesPlaceIdLazyRoute
  '/_layout/_left-detail/events/madhyapur-festival/$': typeof LayoutLeftDetailEventsMadhyapurFestivalSplatRoute
  '/_layout/_left-detail/place/$osmId/$': typeof LayoutLeftDetailPlaceOsmIdSplatRoute
  '/_layout/directions/$locations/$mode/$': typeof LayoutDirectionsLocationsModeSplatLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/$'
    | '/contributions'
    | '/add-place/$'
    | '/report-incident/$'
    | '/nearby/$amenity/$'
    | '/places/$placeId'
    | '/events/madhyapur-festival/$'
    | '/place/$osmId/$'
    | '/directions/$locations/$mode/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/$'
    | '/contributions'
    | '/add-place/$'
    | '/report-incident/$'
    | '/nearby/$amenity/$'
    | '/places/$placeId'
    | '/events/madhyapur-festival/$'
    | '/place/$osmId/$'
    | '/directions/$locations/$mode/$'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_left-detail'
    | '/_layout/$'
    | '/_layout/contributions'
    | '/_layout/add-place/$'
    | '/_layout/report-incident/$'
    | '/_layout/nearby/$amenity/$'
    | '/_layout/_left-detail/places/$placeId'
    | '/_layout/_left-detail/events/madhyapur-festival/$'
    | '/_layout/_left-detail/place/$osmId/$'
    | '/_layout/directions/$locations/$mode/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_left-detail",
        "/_layout/$",
        "/_layout/contributions",
        "/_layout/add-place/$",
        "/_layout/report-incident/$",
        "/_layout/nearby/$amenity/$",
        "/_layout/directions/$locations/$mode/$"
      ]
    },
    "/_layout/_left-detail": {
      "filePath": "_layout/_left-detail.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_left-detail/places/$placeId",
        "/_layout/_left-detail/events/madhyapur-festival/$",
        "/_layout/_left-detail/place/$osmId/$"
      ]
    },
    "/_layout/$": {
      "filePath": "_layout/$.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/contributions": {
      "filePath": "_layout/contributions.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/add-place/$": {
      "filePath": "_layout/add-place/$.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/report-incident/$": {
      "filePath": "_layout/report-incident/$.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/nearby/$amenity/$": {
      "filePath": "_layout/nearby.$amenity.$.tsx",
      "parent": "/_layout"
    },
    "/_layout/_left-detail/places/$placeId": {
      "filePath": "_layout/_left-detail.places.$placeId.lazy.tsx",
      "parent": "/_layout/_left-detail"
    },
    "/_layout/_left-detail/events/madhyapur-festival/$": {
      "filePath": "_layout/_left-detail.events.madhyapur-festival.$.tsx",
      "parent": "/_layout/_left-detail"
    },
    "/_layout/_left-detail/place/$osmId/$": {
      "filePath": "_layout/_left-detail.place.$osmId.$.tsx",
      "parent": "/_layout/_left-detail"
    },
    "/_layout/directions/$locations/$mode/$": {
      "filePath": "_layout/directions.$locations.$mode.$.lazy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
